// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXqoTko9ORY3O8c5mt9-QIH2mef3tYCoo',
    appId: '1:756518976496:web:6027507084f19178f2fb35',
    messagingSenderId: '756518976496',
    projectId: 'bronx-science-nhs-e9bcc',
    authDomain: 'bronx-science-nhs-e9bcc.firebaseapp.com',
    storageBucket: 'bronx-science-nhs-e9bcc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvfZGRt24zDV8V_g7tdYksIB5NPO7Sxok',
    appId: '1:756518976496:android:e70ed670c4892958f2fb35',
    messagingSenderId: '756518976496',
    projectId: 'bronx-science-nhs-e9bcc',
    storageBucket: 'bronx-science-nhs-e9bcc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQz_sqU9fvbZyciFxJHXrJUlSsLwU9bFk',
    appId: '1:756518976496:ios:9d9af8e676b112ecf2fb35',
    messagingSenderId: '756518976496',
    projectId: 'bronx-science-nhs-e9bcc',
    storageBucket: 'bronx-science-nhs-e9bcc.appspot.com',
    iosClientId: '756518976496-m037ahk5i2td4paes6ek2s66bpnbasa0.apps.googleusercontent.com',
    iosBundleId: 'com.example.nhs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQz_sqU9fvbZyciFxJHXrJUlSsLwU9bFk',
    appId: '1:756518976496:ios:9d9af8e676b112ecf2fb35',
    messagingSenderId: '756518976496',
    projectId: 'bronx-science-nhs-e9bcc',
    storageBucket: 'bronx-science-nhs-e9bcc.appspot.com',
    iosClientId: '756518976496-m037ahk5i2td4paes6ek2s66bpnbasa0.apps.googleusercontent.com',
    iosBundleId: 'com.example.nhs',
  );
}
